### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by CB987**
Adds additional `bundle exec` to docker command; while adding `bundle exec` to the rails command made more progress than initially, needed it on the rake command as well to start the server. change to `&&` comes from avalon/docker-compose.

### CODE REVIEW

**Comment by CB987** [comment]
This is related to PR #59.

**Review by apertome — APPROVED** [review]
Looks good

**Comment by apertome** [comment]
Thank  you @CB987 !

**Comment by CB987** [comment]
Thank you!

**Pull request merged**
